trigger:
- main

pool:
  vmImage:  'ubuntu-latest'

jobs:
- job: gradleCheck
  displayName: Run check
  steps:
  - task: Gradle@2
    inputs:
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '11'
      tasks: 'check'
