[versions]
slf4j = { strictly = "[2.0.7, 2.1[", prefer = "2.0.7" }
junit = "4.13.1"
junit5 = "5.8.2"

[libraries]
slf4j-api = {group = "org.slf4j", name = "slf4j-api",  version.ref = "slf4j"}
slf4j-simple = {group = "org.slf4j", name = "slf4j-simple",  version.ref = "slf4j"}
junit4 = {group = "junit", name = "junit", version.ref = "junit"}
junit-jupiter = {group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5"}

[plugins]
spotbugs = {id = "com.github.spotbugs", version = "5.1.3"}
spotless = {id = "com.diffplug.spotless", version = "6.22.0"}
git-version = {id = "com.palantir.git-version", version = "3.0.0"}
nexus-publish = {id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0-rc-1"}
