when:
  - event: pull_request
    repo: miurahr/java-swing-extra-locales
  - event: push
    branch: [main, releases/*]

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 1
      lfs: false
      tags: true

steps:
  build:
    image: adoptopenjdk/openjdk11:alpine
    commands:
      - apk add --no-cache xvfb xvfb-run libsm-dev libxrender libxext-dev libxtst-dev libxcb-dev ttf-dejavu font-xfree86-type1 font-sun-misc
      - xvfb-run -a --server-args='-screen 0, 1024x768x24' ./gradlew --no-daemon clean check
