when:
  - event: pull_request
  - event: tag
    ref: refs/tags/v*
  - event: push
    branch: [main, releases/*]

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 1
      lfs: false
      tags: true

steps:
  build:
    image: adoptopenjdk/openjdk11:alpine
    commands:
      - ./gradlew --no-daemon clean build
