name: Upload Assets to OSSRH

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: setup xvfb environment
      run: sudo apt-get install -f -q xvfb libsm-dev libxrender1 libxext-dev libxtst-dev libxcb1-dev fonts-dejavu xfonts-base xfonts-scalable
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Get the version
      id: get_version
      run: |
        REV_COUNT=`git rev-list --count HEAD`
        echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Run gradle build
      run: xvfb-run -a --server-args='-screen 0, 1024x768x24' ./gradlew -PenvIsCi=true build
      id: gradle
    - name: Publish package to OSSRH
      run: ./gradlew publishToSonatype
      env:
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SECRET_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_KEY_PASSPHARASE }}
        SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
        SONATYPE_PASS: ${{ secrets.SONATYPE_PASS }}
